version: '3'
services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    volumes:
      - $PWD/app:/app
    command: /bin/sh -c "npm install && npm run dev"
    tty: true
    ports:
      - 3000:3000
    environment:
      POSTGRES_HOST: postgresql
      POSTGRES_PORT: 5432
      POSTGRES_USER: user
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: animal_sound
    depends_on:
      - postgresql
  postgresql:
    container_name: postgresql
    build:
      context: .
      dockerfile: docker/postgresql/Dockerfile
    restart: always
    ports:
      - 5432:5432
    volumes:
      - db-store:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: animal_sound

volumes:
  db-store: