version: '3'
services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    volumes:
      - $PWD/app:/app
    command: /bin/sh -c "npm install && npm run dev"
    tty: true
    ports:
      - 3000:3000
  #  environment:
  #    POSTGRES_HOST: postgresql
  #    POSTGRES_PORT: 5432
  #    POSTGRES_USER: user
  #    POSTGRES_PASSWORD: postgres
  #    POSTGRES_DB: animal_sound
  #  depends_on:
  #    - postgresql
  #postgresql:
  #  container_name: postgresql
  #  build:
  #    context: .
  #    dockerfile: docker/postgresql/Dockerfile
  #  restart: always
  #  ports:
  #    - 5432:5432
  #  volumes:
  #    - db-store:/var/lib/postgresql/data
  #  environment:
  #    POSTGRES_USER: user
  #    POSTGRES_PASSWORD: postgres
  #    POSTGRES_DB: animal_sound

  minio:
    container_name: minio
    build:
      context: .
      dockerfile: docker/minio/Dockerfile
    ports:
      - 9000:9000 # データAPI
      - 9090:9090 # 管理画面
    volumes:
      - minio-store:/var/lib/minio/data
    environment:
      MINIO_ACCESS_KEY: minio_root
      MINIO_SECRET_KEY: minio_password
    command: server --console-address ":9090" /var/lib/minio/data

  minio_mc:
    container_name: minio_mc
    build:
      context: .
      dockerfile: docker/minio_mc/Dockerfile
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
        /usr/bin/mc alias set minio http://minio:9000 minio_root minio_password;
        /usr/bin/mc mb minio/sample;
        exit 0;
      "

volumes:
  minio-store:
#  db-store:
